version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - ai_net

  node-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node-api
    ports:
      - "3000:3000"
    volumes:
      - ./metrics.db:/app/metrics.db
    depends_on:
      - redis
    networks:
      - ai_net

  python-agent:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-agent
    volumes:
      - ./metrics.db:/app/metrics.db
    depends_on:
      - redis
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge
